# Generated by Django 5.1.3 on 2024-11-28 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('adresse', models.TextField()),
                ('webseite', models.URLField(blank=True)),
                ('erstellt', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
