# Generated by Django 5.1.3 on 2024-11-28 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_rename_profil_profile'),
        ('receivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rechnungsnummer', models.CharField(max_length=150)),
                ('erfüllungsdatum', models.DateField()),
                ('rechnungsdatum', models.DateField()),
                ('zahlungsziel', models.DateField()),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('abgeschlossen', models.BooleanField(default=False)),
                ('empfänger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receivers.receiver')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
