# Generated by Django 5.1.3 on 2024-11-28 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leistung', models.CharField(max_length=200)),
                ('beschreibung', models.TextField(blank=True, help_text='Optionale Info')),
                ('betrag', models.FloatField(help_text='in EUR €')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('rechnung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.invoice')),
            ],
        ),
    ]
